Make `trixi_include` more flexible by allowing a mapping to be passed
trixi-framework/TrixiBase.jl pull request #35
Opened 2024-12-23 19:02 UTC by efaulhaber

2024-12-24 00:04 UTC, sloede reviewed
Fine by me, though I do not really understand most of the changes 😅. Would be good if @ranocha could give the final green light :-)

2025-01-09 08:12 UTC, ranocha requested changes
Thanks! Why do you need this functionality?

2025-01-09 08:12 UTC, ranocha commented on src/trixi_include.jl
> +function trixi_include(mapexpr::Function, mod::Module, elixir::AbstractString; kwargs...)
Please update the docstring accordingly

2025-01-09 08:12 UTC, ranocha commented on src/trixi_include.jl
> +                 mod, elixir)
```suggestion
    Base.include(replace_assignments ∘ insert_maxiters ∘ mapexpr; kwargs...),
                 mod, elixir)
```

2025-01-09 08:12 UTC, ranocha commented on src/trixi_include.jl
> +    Base.include(ex -> replace_assignments(insert_maxiters(mapexpr(ex)); kwargs...),
Why did you choose this order of operations?

2025-01-09 09:55 UTC, efaulhaber commented on src/trixi_include.jl
> +    Base.include(ex -> replace_assignments(insert_maxiters(mapexpr(ex)); kwargs...),
I thought about it and couldn't come up with a reason for any order, so I just chose this one.

2025-01-09 09:56 UTC, efaulhaber commented on src/trixi_include.jl
> +                 mod, elixir)
Well, the Trixi style guide says:
> Executable code should only use ASCII characters.

2025-01-09 10:09 UTC, efaulhaber commented
> Thanks! Why do you need this functionality?

I want to add a macro `trixi_include_changeprecision` to TrixiParticles that behaves like `trixi_include`, but uses [ChangePrecision.jl](https://github.com/JuliaMath/ChangePrecision.jl) to change the precision of an elixir to `Float32` to run it on GPUs.

I could also add this macro to TrixiBase, but so far it will only be used by TrixiParticles.

https://github.com/trixi-framework/TrixiParticles.jl/blob/ef/more-gpu-support/src/util.jl#L138-L163

2025-01-09 11:18 UTC, ranocha commented on src/trixi_include.jl
> +    Base.include(ex -> replace_assignments(insert_maxiters(mapexpr(ex)); kwargs...),
👍

2025-01-09 11:18 UTC, ranocha commented
> > Thanks! Why do you need this functionality?
> 
> I want to add a macro `trixi_include_changeprecision` to TrixiParticles that behaves like `trixi_include`, but uses [ChangePrecision.jl](https://github.com/JuliaMath/ChangePrecision.jl) to change the precision of an elixir to `Float32` to run it on GPUs.
> 
> I could also add this macro to TrixiBase, but so far it will only be used by TrixiParticles.
> 
> https://github.com/trixi-framework/TrixiParticles.jl/blob/ef/more-gpu-support/src/util.jl#L138-L163

This would be nice to have here

2025-01-09 11:21 UTC, ranocha commented on src/trixi_include.jl
> +                 mod, elixir)
@sloede? Composing functions is only available using `∘`. From my point of view, `∘` makes it easier to read the code in this case.

2025-01-14 09:57 UTC, efaulhaber commented
I now moved the macro from TrixiParticles to this PR.

2025-01-15 08:50 UTC, ranocha commented on src/trixi_include.jl
> +Most code in the Trixi framework is written in a way that changing all floating-point
```suggestion
Most code in the Trixi.jl framework is written in a way that changing all floating-point
```

2025-01-15 08:50 UTC, ranocha commented on src/trixi_include.jl
> +numbers in the elixir to `Float32` manually will run the full simulation with single precision.
I'm not susosure about this. For example, in Trixi.jl, we need to specify additional stuff like `RealT = Float32` etc. at several places, e.g.,

https://github.com/trixi-framework/Trixi.jl/blob/c69fe96da676f2521889fc79f68f8e6a6b5a4e7e/examples/unstructured_2d_dgsem/elixir_shallowwater_ec_float32.jl

https://github.com/trixi-framework/Trixi.jl/blob/c69fe96da676f2521889fc79f68f8e6a6b5a4e7e/examples/unstructured_2d_dgsem/elixir_shallowwater_ec_float32.jl#L33

https://github.com/trixi-framework/Trixi.jl/blob/c69fe96da676f2521889fc79f68f8e6a6b5a4e7e/examples/p4est_2d_dgsem/elixir_euler_shockcapturing_ec_float32.jl#L14

2025-01-15 14:52 UTC, efaulhaber commented on src/trixi_include.jl
> +numbers in the elixir to `Float32` manually will run the full simulation with single precision.
So how do I formulate the purpose of the macro then? In TrixiParticles, we only need to change everything to `Float32` and the full simulation runs with single precision.

Maybe something like
```suggestion
Many constructors in the Trixi.jl framework are written in a way that changing all floating-point
arguments to `Float32` will change the element type to `Float32` as well.
In TrixiParticles.jl, including an elixir with this macro should be sufficient
to run the full simulation with single precision.
```

2025-01-15 19:28 UTC, ranocha commented on src/trixi_include.jl
> +numbers in the elixir to `Float32` manually will run the full simulation with single precision.
👍

2025-01-15 19:30 UTC, ranocha reviewed
Could you please add a test before we merge this PR?

2025-01-16 10:13 UTC, sloede commented on src/trixi_include.jl
> +                 mod, elixir)
Fine by me.

2025-01-16 10:16 UTC, sloede reviewed
LGTM in general and is certainly an interesting feature!

Before merging, I second @ranocha in that there should be a test for this - maybe using some temporary Julia file that will return a double floating point value but will then be changed to returning a `Float32` value?

2025-01-16 10:21 UTC, efaulhaber commented on src/trixi_include.jl
> +                 mod, elixir)
Just realized it doesn't work like this because the kwargs are passed to `insert_maxiters`.

2025-01-16 10:46 UTC, efaulhaber commented
Back to @ranocha's question:
> Why did you choose this order of operations?

I just changed it to first replace assignments and then call `mapexpr`. This means that ChangePrecision is called on top of the replaced elixir. Thus,
```julia
trixi_include_changeprecision(Float32, elixir; density=1000.0)
```
will make `density` a `Float32`.
I think this is the most intuitive and least error-prone option. Especially when writing things where this is less obvious like
```julia
trixi_include_changeprecision(Float32, elixir; density=ones(nparticles))
```
Here, `ones` will be changed by ChangePrecision to `ones(Float32, ...)`.

I also added tests for this.

2025-01-16 10:59 UTC, efaulhaber commented on src/trixi_include.jl
> +end
One more problem here. This doesn't work when, for some reason, we would include an elixir that looks like this:
```julia
using TrixiBase

TrixiBase.trixi_include(...)
```

It only works when we directly write the elixir as
```julia
using TrixiBase

trixi_include(...)
```

@ranocha any ideas how to fix this?

2025-01-16 13:08 UTC, sloede commented on src/trixi_include.jl
> +end
Can you special case this with something like Symbol("TrixiBase.trixi_include")?

Alternatively, @vchuravy might have an idea how this can be done?

2025-01-16 13:10 UTC, sloede commented on src/trixi_include.jl
> +end
This function seems to be missing from the tests ([codecov](https://app.codecov.io/gh/trixi-framework/TrixiBase.jl/pull/35?dropdown=coverage&src=pr&el=h1&utm_medium=referral&utm_source=github&utm_content=checks&utm_campaign=pr+comments&utm_term=trixi-framework#6c93ba47319f3776d466449ad1a742ff-R91))

2025-01-16 13:13 UTC, efaulhaber commented on src/trixi_include.jl
> +end
I tried, didn't work. Also, we would need to add a special case for each package that re-exports this name.

2025-01-16 13:15 UTC, sloede commented on test/trixi_include.jl
> +        filename = tempname()
Why handle tempfile generation and deletion manually instead of using the automatic cleanup of a `do` block with [`Base.Filesystem.mktemp`](https://docs.julialang.org/en/v1/base/file/#Base.Filesystem.mktemp-Tuple{Function,%20AbstractString})?

2025-01-16 16:44 UTC, efaulhaber commented on test/trixi_include.jl
> +        filename = tempname()
Why did you do it when you updated these files last year? 🙃

2025-01-16 16:50 UTC, efaulhaber commented on test/trixi_include.jl
> +        filename = tempname()
Updated all tests to use `mktemp`.

2025-01-17 05:35 UTC, sloede commented on test/trixi_include.jl
> +        filename = tempname()
> Why did you do it when you updated these files last year? 🙃

🙈 Good question, I do not remember. I assume mindless copy pasta.

2025-01-17 05:35 UTC, sloede commented on test/trixi_include.jl
> +        filename = tempname()
Thanks!

2025-01-17 05:38 UTC, sloede reviewed
LGTM! Let's wait and see if @vchuravy has an easy solution for the open conversation (if not, we can go ahead anyways)

2025-01-17 10:15 UTC, vchuravy commented on src/trixi_include.jl
> +end
This will be a `GlobalRef(mod, name)`.

So `x.args[1] isa GlobalRef` and then check the name and replace it.

2025-01-23 10:45 UTC, efaulhaber commented on src/trixi_include.jl
> +end
Doesn't work. `x.args[1] isa GlobalRef` is `false`.

2025-01-23 14:46 UTC, vchuravy commented on src/trixi_include.jl
> +end
What is `x.args[1]` when it is the case that doesn't work?

2025-01-23 15:19 UTC, efaulhaber commented on src/trixi_include.jl
> +end
`x.head = :call` and `x.args[1] = :(TrixiParticles.trixi_include)`

2025-01-23 15:21 UTC, ranocha commented on src/trixi_include.jl
> +end
Why do you want to write `TrixiParticles.trixi_include` instead of `trixi_include`?

2025-01-23 15:44 UTC, vchuravy commented on src/trixi_include.jl
> +end
```
julia> dump(:(TrixiParticles.trixi_include))
Expr
  head: Symbol .
  args: Array{Any}((2,))
    1: Symbol TrixiParticles
    2: QuoteNode
      value: Symbol trixi_include
```

Ah so this is before resolution, you will have the issue that someone might also write: 

```
Main.TrixiParticles.trixi_include
```

in any arbitrary depth and length.

2025-01-23 15:45 UTC, efaulhaber commented on src/trixi_include.jl
> +end
So is there a simple solution for this? Or do we just ignore this case?

2025-01-23 15:46 UTC, ranocha commented on src/trixi_include.jl
> +end
The most simple hack would be to check specifically then whether we have `Trixi.trixi_include` or `TrixiParticles.trixi_include`. Alternatively, you could try

```suggestion
function replace_trixi_include(T, expr)
    expr = TrixiBase.walkexpr(expr) do x
        if x isa Expr
            # allow `trixi_include(...)` and `Trixi.trixi_include(...)` etc.
            split_arg = split(string(x.args[1]), '.')
            if x.head === :call && split_arg[end] == "trixi_include"
                arg_pefix = join(split_args[begin:(end - 1)], '.')
                x.args[1] = Symbol(arg_pefix * "trixi_include_changeprecision")
                insert!(x.args, 2, :($T))
            end
        end
        return x
    end

    return expr
end
```

2025-01-23 15:54 UTC, efaulhaber commented on src/trixi_include.jl
> +end
```
julia> TrixiBase.trixi_include_changeprecision(Float32, "../TrixiBase.jl/test1.jl")
[ Info: You just called `trixi_include`. Julia may now compile the code, please be patient.
ERROR: LoadError: UndefVarError: `TrixiBase.trixi_include_changeprecision` not defined in `Main`
Suggestion: check for spelling errors or missing imports.
```

2025-01-23 16:34 UTC, ranocha commented on src/trixi_include.jl
> +end
But it looks like `TrixiBase.trixi_include_changeprecision` is defined... Does your test file create a module? How does it import `trixi_include`?

2025-01-24 09:09 UTC, efaulhaber commented on src/trixi_include.jl
> +end
Idk. The test file just contains this single line:
```julia
TrixiBase.trixi_include("test2.jl")
```
And the error message says we're in `Main`.

2025-01-24 13:46 UTC, efaulhaber commented on src/trixi_include.jl
> +end
Or should we merge it as is and discuss this in an issue? I don't feel like wasting more time on this edge case.

2025-01-28 08:38 UTC, ranocha commented on src/trixi_include.jl
> +    trixi_include([mapexpr::Function,] [mod::Module=Main,] elixir::AbstractString; kwargs...)
```suggestion
    trixi_include([mapexpr::Function=identity,] [mod::Module=Main,] elixir::AbstractString; kwargs...)
```

2025-01-28 08:39 UTC, ranocha approved these changes
Thanks! Let's merge this as it is and discuss possible improvements in an issue

2025-01-28 08:45 UTC, merged